name: Test Check
on:
  pull_request:
    branches: [main]
jobs:
  test:
    env:
      NEXT_PUBLIC_SANITY_DATASET: ${{ vars.NEXT_PUBLIC_SANITY_DATASET }}
      NEXT_PUBLIC_SANITY_PROJECT_ID: ${{ vars.NEXT_PUBLIC_SANITY_PROJECT_ID }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Initialize environment
        uses: ./.github/actions/init

      - name: Run tests
        run: npm test
